#! /bin/sh

### BEGIN INIT INFO
# Provides:		netcheck 
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	netcheck server
### END INIT INFO

set -e

# /etc/init.d/netcheck: start and stop the netcheck daemon

if test -f /etc/default/netcheck; then
    . /etc/default/netcheck
fi

test -x $NETCHECKSH || exit 0

umask 022

. /lib/lsb/init-functions

[ -n "$2" ] && NETCHECK_OPTS="$NETCHECK_OPTS $2"

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

# $NETCHECKSH $NETCHECK_OPTS || exit 1

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin:/home/mkronvold/src/netcheck"

case "$1" in
  start)
	log_daemon_msg "Starting Netcheck service" "netcheck" || true
	# shellcheck disable=SC2086
	if start-stop-daemon --start --background --quiet --oknodo --chuid 0:0 --pidfile /run/netcheck.pid --make-pidfile --startas $NETCHECKSH -- $NETCHECK_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping Netcheck server" "netcheck" || true
	if start-stop-daemon --stop --quiet --oknodo --retry 10 --pidfile /run/netcheck.pid --exec $NETCHECKSH; then
	    log_end_msg 0 || true
	    kill $(cat /run/netcheck.pid) 2> /dev/null
	else
	    log_end_msg 1 || true
	    kill $(cat /run/netcheck.pid) 2> /dev/null
	fi
	;;
  restart)
	log_daemon_msg "Restarting Netcheck server" "netcheck" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /run/netcheck.pid --exec $NETCHECKSH
	# shellcheck disable=SC2086
	if start-stop-daemon --start --background --quiet --oknodo --chuid 0:0 --pidfile /run/netcheck.pid --make-pidfile --startas $NETCHECKSH -- $NETCHECK_OPTS; then
	    log_end_msg 0 || true
	    kill $(cat /run/netcheck.pid) 2> /dev/null
	else
	    log_end_msg 1 || true
	    kill $(cat /run/netcheck.pid) 2> /dev/null
	fi
	;;
  status)
	#	status_of_proc -p /run/netcheck.pid $NETCHECKSH netcheck && exit 0 || exit $?
      	status_of_proc -p /run/netcheck.pid netcheck && exit 0 || exit $?
	;;
  *)
	log_action_msg "Usage: /etc/init.d/netcheck {start|stop|reload|force-reload|restart|try-restart|status}" || true
	exit 1
esac

exit 0
